version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - backend_files:/backend
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  server:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - web

volumes:
  postgres_data:
  backend_files: