# Generated by Django 3.1 on 2022-08-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '1003_generate_test_data_producttemplates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaproductdata',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='metacomponent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='metaproductdata',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='metaservice',
            managers=[
            ],
        ),
    ]
