# Generated by Django 3.1 on 2022-06-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '1003_generate_test_data_producttemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityestimate',
            name='operation_option_label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
