# Generated by Django 3.1 on 2022-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '1004_auto_20220805_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
