# Generated by Django 3.1 on 2020-11-16 09:45
from django.db import migrations
from core.utils.measures import Measure
from inventory.models import BaseStockUnit, AlternateStockUnit


def create_uoms(apps, schema_editor):
    box_alt_uom = AlternateStockUnit.objects.create(name='Box', abbrev='box', is_editable=False)

    for uom in [('pc', 'Piece'), ('sheet', 'Sheet')]:
        abbrev, name = uom
        base_uom = BaseStockUnit.objects.create(name=name, abbrev=abbrev, is_editable=False)
        box_alt_uom.base_stock_units.add(base_uom)

    sheet_base_uom = BaseStockUnit.objects.get(name='Sheet')

    for uom in [('pad', 'Pad'), ('set', 'Set'), ('booklet', 'Booklet'), ('ream', 'Ream')]:
        abbrev, name = uom
        alt_uom = AlternateStockUnit.objects.create(name=name, abbrev=abbrev, is_editable=False)
        alt_uom.base_stock_units.add(sheet_base_uom)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_uoms, reverse_code=migrations.RunPython.noop)
    ]
